apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: backend
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: system-design
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
