== ДЗ 1
2026.01.16

. (+) Подготовил требования: ФТ, НФТ, риски
. (+) Спроектировал высокоуровневую архитектуру: подготовил контекстную диаграмму.
. (+) Выбран архитектурный стиль, подготовлено описание и обоснование.
. (+) Подготовлено описание пользователей решения
. (+) Описаны внешние интеграции
. (+) Подготовлено описание потоков данных, высокоуровневые взаимодействия и критичность компонентов.
. (+) Подготовлено описание модели данных

== ДЗ 2
2026.02.09

. (+) Выполнены расчёты показателей производительности (doc 2.07).
. (+) Детализирована концептуальная схема архитектуры (doc 2.08) с учётом высокой доступности, отказоустойчивости, масштабирования и производительности.
. (+) Расширена система мониторинга в LikeC4.
. (+) Описана observability (doc 2.09): требования к системным и бизнесовым метрикам, алерты и пороги.
. (+) Разработан план реагирования на отклонения (doc 2.10): за чем наблюдаем , пороги и действия, эскалация L1–L3, runbook.
. (+) Разработан план DR (doc 2.10): RTO/RPO по классам данных, резервное копирование , сценарии отказов, роли и контакты; мероприятия по проверке DR .
. (+) В LikeC4 детализированы пользователи.
. (+) Добавлены протоколы и описания взаимодействия с внешними системами в LikeC4.
. (+) Добавлены виды диаграмм LikeC4 и экспорт в PlantUML. 
. (+) Схемы доступны для интерактивного просмотра: https://shelepovg.github.io/system-design-homework/
