@startuml
title "Контекстная диаграмма"
top to bottom direction

hide stereotype
skinparam ranksep 60
skinparam nodesep 30
skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  shadowing false
}

skinparam rectangle<<Users>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<SystemMonitoring>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<SystemLoadBalancer>>{
  BackgroundColor #23a2d9
  FontColor #ffffff
  BorderColor #1892c5
}
skinparam rectangle<<SystemFront>>{
  BackgroundColor #23a2d9
  FontColor #ffffff
  BorderColor #1892c5
}
skinparam rectangle<<SystemApiGateway>>{
  BackgroundColor #23a2d9
  FontColor #ffffff
  BorderColor #1892c5
}
skinparam rectangle<<SystemIam>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<SystemBackend>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<SystemStorage>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<System_ext>>{
  BackgroundColor #827a8e
  FontColor #ffffff
  BorderColor #6c6477
}
rectangle "Пользователи\n\nКлиенты: веб-браузер, Android, iOS" <<Users>> as Users
rectangle "Система" <<System>> as System {
  skinparam RectangleBorderColor<<System>> #2b85e7
  skinparam RectangleFontColor<<System>> #2b85e7
  skinparam RectangleBorderStyle<<System>> dashed

  rectangle "Система мониторинга\n\nСбор логов и метрик, обработка, хранение, дашборды и алертинг" <<SystemMonitoring>> as SystemMonitoring
  rectangle "load-balancer\n<size:10>[[Nginx]]</size>\n\nЕдиная точка входа: распределение трафика, TLS termination" <<SystemLoadBalancer>> as SystemLoadBalancer
  rectangle "front\n<size:10>[[React]]</size>\n\nВеб-интерфейс для взаимодействия с системой" <<SystemFront>> as SystemFront
  rectangle "api-gateway\n<size:10>[Spring Cloud Gateway]</size>\n\nМаршрутизация API, аутентификация, авторизация, rate limiting" <<SystemApiGateway>> as SystemApiGateway
  rectangle "iam\n<size:10>[[Keycloak]]</size>\n\nIdentity and Access Management" <<SystemIam>> as SystemIam
  rectangle "Обработка пользовательских запросов\n<size:10>[[Spring]]</size>\n\nСистема обработки бизнес-логики" <<SystemBackend>> as SystemBackend
  rectangle "Хранение данных\n\nХранение данных пользователя" <<SystemStorage>> as SystemStorage
}
rectangle "Внешние системы\n\nВнешние системы" <<System_ext>> as System_ext

Users .[#8D8D8D,thickness=2].> SystemLoadBalancer : <color:#8D8D8D>[...]
SystemLoadBalancer .[#8D8D8D,thickness=2].> SystemFront
SystemMonitoring .[#8D8D8D,thickness=2].> SystemLoadBalancer : <color:#8D8D8D>[...]
SystemFront .[#8D8D8D,thickness=2].> SystemApiGateway
SystemMonitoring .[#8D8D8D,thickness=2].> SystemFront : <color:#8D8D8D>[...]
SystemApiGateway .[#8D8D8D,thickness=2].> SystemIam : <color:#8D8D8D>Валидация JWT и проверка прав
SystemApiGateway .[#8D8D8D,thickness=2].> SystemBackend
SystemMonitoring .[#8D8D8D,thickness=2].> SystemApiGateway : <color:#8D8D8D>[...]
SystemMonitoring .[#8D8D8D,thickness=2].> SystemIam : <color:#8D8D8D>[...]
SystemBackend .[#8D8D8D,thickness=2].> SystemStorage : <color:#8D8D8D>Чтение и запись данных
SystemMonitoring .[#8D8D8D,thickness=2].> SystemBackend : <color:#8D8D8D>[...]
SystemMonitoring .[#8D8D8D,thickness=2].> SystemStorage : <color:#8D8D8D>[...]
SystemApiGateway .[#8D8D8D,thickness=2].> System_ext : <color:#8D8D8D>Проверка токенов и синхронизация \n<color:#8D8D8D>пользователей
SystemBackend .[#8D8D8D,thickness=2].> System_ext : <color:#8D8D8D>[...]
@enduml
