@startuml
title "Контекстная диаграмма"
top to bottom direction

hide stereotype
skinparam ranksep 60
skinparam nodesep 30
skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  shadowing false
}

skinparam person<<Users>>{
  BackgroundColor #827a8e
  FontColor #ffffff
  BorderColor #6c6477
}
skinparam rectangle<<SystemMonitoring>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<SystemFront>>{
  BackgroundColor #23a2d9
  FontColor #ffffff
  BorderColor #1892c5
}
skinparam rectangle<<SystemApiGateway>>{
  BackgroundColor #23a2d9
  FontColor #ffffff
  BorderColor #1892c5
}
skinparam rectangle<<SystemIam>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<SystemBackend>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<Iam_ext>>{
  BackgroundColor #827a8e
  FontColor #ffffff
  BorderColor #6c6477
}
skinparam rectangle<<SystemStorage>>{
  BackgroundColor #2b85e7
  FontColor #f1ffff
  BorderColor #1e73ce
}
skinparam rectangle<<Payment>>{
  BackgroundColor #827a8e
  FontColor #ffffff
  BorderColor #6c6477
}
skinparam rectangle<<Notification>>{
  BackgroundColor #827a8e
  FontColor #ffffff
  BorderColor #6c6477
}
person "==Пользователи\n\nПользователи системы" <<Users>> as Users
rectangle "Система" <<System>> as System {
  skinparam RectangleBorderColor<<System>> #2b85e7
  skinparam RectangleFontColor<<System>> #2b85e7
  skinparam RectangleBorderStyle<<System>> dashed

  rectangle "==Система мониторинга\n\nМониторинг состояния системы" <<SystemMonitoring>> as SystemMonitoring
  rectangle "==front\n<size:10>[[React]]</size>\n\nВеб-интерфейс для взаимодействия с системой" <<SystemFront>> as SystemFront
  rectangle "==api-gateway\n<size:10>[Sping Cloud Gateway]</size>\n\nОбработка входящих запросов, маршрутизация, аутентификация и авторизация" <<SystemApiGateway>> as SystemApiGateway
  rectangle "==iam\n<size:10>[[Keycloak]]</size>\n\nIdentity and Access Management" <<SystemIam>> as SystemIam
  rectangle "==Обработка пользовательских запросов\n<size:10>[[Spring]]</size>\n\nСистема обработки бизнес-логики" <<SystemBackend>> as SystemBackend
  rectangle "==Хранение данных\n\nХранение данных пользователя" <<SystemStorage>> as SystemStorage
}
rectangle "==IAM\n<size:10>[[OAuth2]]</size>\n\nВнешняя система аутентификации" <<Iam_ext>> as Iam_ext
rectangle "==Платежная система\n\nОбработка платежей" <<Payment>> as Payment
rectangle "==Уведомления\n\nОтправка уведомлений пользователям" <<Notification>> as Notification

Users .[#8D8D8D,thickness=2].> SystemFront
SystemFront .[#8D8D8D,thickness=2].> SystemApiGateway
SystemMonitoring .[#8D8D8D,thickness=2].> SystemFront
SystemApiGateway .[#8D8D8D,thickness=2].> SystemIam
SystemApiGateway .[#8D8D8D,thickness=2].> SystemBackend
SystemMonitoring .[#8D8D8D,thickness=2].> SystemApiGateway
SystemMonitoring .[#8D8D8D,thickness=2].> SystemIam
SystemBackend .[#8D8D8D,thickness=2].> SystemStorage
SystemMonitoring .[#8D8D8D,thickness=2].> SystemBackend
SystemMonitoring .[#8D8D8D,thickness=2].> SystemStorage
SystemApiGateway .[#8D8D8D,thickness=2].> Iam_ext
SystemBackend .[#8D8D8D,thickness=2].> Payment
SystemBackend .[#8D8D8D,thickness=2].> Notification
@enduml
